typedef signed char int8_t;
typedef short int int16_t;
typedef int int32_t;
typedef long int int64_t;
typedef unsigned char uint8_t;
typedef unsigned short int uint16_t;
typedef unsigned int uint32_t;
typedef unsigned long int uint64_t;
typedef signed char int_least8_t;
typedef short int int_least16_t;
typedef int int_least32_t;
typedef long int int_least64_t;
typedef unsigned char uint_least8_t;
typedef unsigned short int uint_least16_t;
typedef unsigned int uint_least32_t;
typedef unsigned long int uint_least64_t;
typedef signed char int_fast8_t;
typedef long int int_fast16_t;
typedef long int int_fast32_t;
typedef long int int_fast64_t;
typedef unsigned char uint_fast8_t;
typedef unsigned long int uint_fast16_t;
typedef unsigned long int uint_fast32_t;
typedef unsigned long int uint_fast64_t;
typedef long int intptr_t;
typedef unsigned long int uintptr_t;
typedef long int intmax_t;
typedef unsigned long int uintmax_t;
typedef int32_t khronos_int32_t;
typedef uint32_t khronos_uint32_t;
typedef int64_t khronos_int64_t;
typedef uint64_t khronos_uint64_t;
typedef signed char khronos_int8_t;
typedef unsigned char khronos_uint8_t;
typedef signed short int khronos_int16_t;
typedef unsigned short int khronos_uint16_t;
typedef signed long int khronos_intptr_t;
typedef unsigned long int khronos_uintptr_t;
typedef signed long int khronos_ssize_t;
typedef unsigned long int khronos_usize_t;
typedef float khronos_float_t;
typedef khronos_uint64_t khronos_utime_nanoseconds_t;
typedef khronos_int64_t khronos_stime_nanoseconds_t;
typedef enum {
    KHRONOS_FALSE = 0,
    KHRONOS_TRUE = 1,
    KHRONOS_BOOLEAN_ENUM_FORCE_SIZE = 0x7FFFFFFF
} khronos_boolean_enum_t;
typedef void GLvoid;
typedef char GLchar;
typedef unsigned int GLenum;
typedef unsigned char GLboolean;
typedef unsigned int GLbitfield;
typedef khronos_int8_t GLbyte;
typedef short GLshort;
typedef int GLint;
typedef int GLsizei;
typedef khronos_uint8_t GLubyte;
typedef unsigned short GLushort;
typedef unsigned int GLuint;
typedef khronos_float_t GLfloat;
typedef khronos_float_t GLclampf;
typedef khronos_int32_t GLfixed;
typedef khronos_intptr_t GLintptr;
typedef khronos_ssize_t GLsizeiptr;
__attribute__((visibility("default"))) void glActiveTexture (GLenum texture);
__attribute__((visibility("default"))) void glAttachShader (GLuint program, GLuint shader);
__attribute__((visibility("default"))) void glBindAttribLocation (GLuint program, GLuint index, const GLchar* name);
__attribute__((visibility("default"))) void glBindBuffer (GLenum target, GLuint buffer);
__attribute__((visibility("default"))) void glBindFramebuffer (GLenum target, GLuint framebuffer);
__attribute__((visibility("default"))) void glBindRenderbuffer (GLenum target, GLuint renderbuffer);
__attribute__((visibility("default"))) void glBindTexture (GLenum target, GLuint texture);
__attribute__((visibility("default"))) void glBlendColor (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha);
__attribute__((visibility("default"))) void glBlendEquation ( GLenum mode );
__attribute__((visibility("default"))) void glBlendEquationSeparate (GLenum modeRGB, GLenum modeAlpha);
__attribute__((visibility("default"))) void glBlendFunc (GLenum sfactor, GLenum dfactor);
__attribute__((visibility("default"))) void glBlendFuncSeparate (GLenum srcRGB, GLenum dstRGB, GLenum srcAlpha, GLenum dstAlpha);
__attribute__((visibility("default"))) void glBufferData (GLenum target, GLsizeiptr size, const GLvoid* data, GLenum usage);
__attribute__((visibility("default"))) void glBufferSubData (GLenum target, GLintptr offset, GLsizeiptr size, const GLvoid* data);
__attribute__((visibility("default"))) GLenum glCheckFramebufferStatus (GLenum target);
__attribute__((visibility("default"))) void glClear (GLbitfield mask);
__attribute__((visibility("default"))) void glClearColor (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha);
__attribute__((visibility("default"))) void glClearDepthf (GLclampf depth);
__attribute__((visibility("default"))) void glClearStencil (GLint s);
__attribute__((visibility("default"))) void glColorMask (GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha);
__attribute__((visibility("default"))) void glCompileShader (GLuint shader);
__attribute__((visibility("default"))) void glCompressedTexImage2D (GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const GLvoid* data);
__attribute__((visibility("default"))) void glCompressedTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const GLvoid* data);
__attribute__((visibility("default"))) void glCopyTexImage2D (GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border);
__attribute__((visibility("default"))) void glCopyTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height);
__attribute__((visibility("default"))) GLuint glCreateProgram (void);
__attribute__((visibility("default"))) GLuint glCreateShader (GLenum type);
__attribute__((visibility("default"))) void glCullFace (GLenum mode);
__attribute__((visibility("default"))) void glDeleteBuffers (GLsizei n, const GLuint* buffers);
__attribute__((visibility("default"))) void glDeleteFramebuffers (GLsizei n, const GLuint* framebuffers);
__attribute__((visibility("default"))) void glDeleteProgram (GLuint program);
__attribute__((visibility("default"))) void glDeleteRenderbuffers (GLsizei n, const GLuint* renderbuffers);
__attribute__((visibility("default"))) void glDeleteShader (GLuint shader);
__attribute__((visibility("default"))) void glDeleteTextures (GLsizei n, const GLuint* textures);
__attribute__((visibility("default"))) void glDepthFunc (GLenum func);
__attribute__((visibility("default"))) void glDepthMask (GLboolean flag);
__attribute__((visibility("default"))) void glDepthRangef (GLclampf zNear, GLclampf zFar);
__attribute__((visibility("default"))) void glDetachShader (GLuint program, GLuint shader);
__attribute__((visibility("default"))) void glDisable (GLenum cap);
__attribute__((visibility("default"))) void glDisableVertexAttribArray (GLuint index);
__attribute__((visibility("default"))) void glDrawArrays (GLenum mode, GLint first, GLsizei count);
__attribute__((visibility("default"))) void glDrawElements (GLenum mode, GLsizei count, GLenum type, const GLvoid* indices);
__attribute__((visibility("default"))) void glEnable (GLenum cap);
__attribute__((visibility("default"))) void glEnableVertexAttribArray (GLuint index);
__attribute__((visibility("default"))) void glFinish (void);
__attribute__((visibility("default"))) void glFlush (void);
__attribute__((visibility("default"))) void glFramebufferRenderbuffer (GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer);
__attribute__((visibility("default"))) void glFramebufferTexture2D (GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level);
__attribute__((visibility("default"))) void glFrontFace (GLenum mode);
__attribute__((visibility("default"))) void glGenBuffers (GLsizei n, GLuint* buffers);
__attribute__((visibility("default"))) void glGenerateMipmap (GLenum target);
__attribute__((visibility("default"))) void glGenFramebuffers (GLsizei n, GLuint* framebuffers);
__attribute__((visibility("default"))) void glGenRenderbuffers (GLsizei n, GLuint* renderbuffers);
__attribute__((visibility("default"))) void glGenTextures (GLsizei n, GLuint* textures);
__attribute__((visibility("default"))) void glGetActiveAttrib (GLuint program, GLuint index, GLsizei bufsize, GLsizei* length, GLint* size, GLenum* type, GLchar* name);
__attribute__((visibility("default"))) void glGetActiveUniform (GLuint program, GLuint index, GLsizei bufsize, GLsizei* length, GLint* size, GLenum* type, GLchar* name);
__attribute__((visibility("default"))) void glGetAttachedShaders (GLuint program, GLsizei maxcount, GLsizei* count, GLuint* shaders);
__attribute__((visibility("default"))) int glGetAttribLocation (GLuint program, const GLchar* name);
__attribute__((visibility("default"))) void glGetBooleanv (GLenum pname, GLboolean* params);
__attribute__((visibility("default"))) void glGetBufferParameteriv (GLenum target, GLenum pname, GLint* params);
__attribute__((visibility("default"))) GLenum glGetError (void);
__attribute__((visibility("default"))) void glGetFloatv (GLenum pname, GLfloat* params);
__attribute__((visibility("default"))) void glGetFramebufferAttachmentParameteriv (GLenum target, GLenum attachment, GLenum pname, GLint* params);
__attribute__((visibility("default"))) void glGetIntegerv (GLenum pname, GLint* params);
__attribute__((visibility("default"))) void glGetProgramiv (GLuint program, GLenum pname, GLint* params);
__attribute__((visibility("default"))) void glGetProgramInfoLog (GLuint program, GLsizei bufsize, GLsizei* length, GLchar* infolog);
__attribute__((visibility("default"))) void glGetRenderbufferParameteriv (GLenum target, GLenum pname, GLint* params);
__attribute__((visibility("default"))) void glGetShaderiv (GLuint shader, GLenum pname, GLint* params);
__attribute__((visibility("default"))) void glGetShaderInfoLog (GLuint shader, GLsizei bufsize, GLsizei* length, GLchar* infolog);
__attribute__((visibility("default"))) void glGetShaderPrecisionFormat (GLenum shadertype, GLenum precisiontype, GLint* range, GLint* precision);
__attribute__((visibility("default"))) void glGetShaderSource (GLuint shader, GLsizei bufsize, GLsizei* length, GLchar* source);
__attribute__((visibility("default"))) const GLubyte* glGetString (GLenum name);
__attribute__((visibility("default"))) void glGetTexParameterfv (GLenum target, GLenum pname, GLfloat* params);
__attribute__((visibility("default"))) void glGetTexParameteriv (GLenum target, GLenum pname, GLint* params);
__attribute__((visibility("default"))) void glGetUniformfv (GLuint program, GLint location, GLfloat* params);
__attribute__((visibility("default"))) void glGetUniformiv (GLuint program, GLint location, GLint* params);
__attribute__((visibility("default"))) int glGetUniformLocation (GLuint program, const GLchar* name);
__attribute__((visibility("default"))) void glGetVertexAttribfv (GLuint index, GLenum pname, GLfloat* params);
__attribute__((visibility("default"))) void glGetVertexAttribiv (GLuint index, GLenum pname, GLint* params);
__attribute__((visibility("default"))) void glGetVertexAttribPointerv (GLuint index, GLenum pname, GLvoid** pointer);
__attribute__((visibility("default"))) void glHint (GLenum target, GLenum mode);
__attribute__((visibility("default"))) GLboolean glIsBuffer (GLuint buffer);
__attribute__((visibility("default"))) GLboolean glIsEnabled (GLenum cap);
__attribute__((visibility("default"))) GLboolean glIsFramebuffer (GLuint framebuffer);
__attribute__((visibility("default"))) GLboolean glIsProgram (GLuint program);
__attribute__((visibility("default"))) GLboolean glIsRenderbuffer (GLuint renderbuffer);
__attribute__((visibility("default"))) GLboolean glIsShader (GLuint shader);
__attribute__((visibility("default"))) GLboolean glIsTexture (GLuint texture);
__attribute__((visibility("default"))) void glLineWidth (GLfloat width);
__attribute__((visibility("default"))) void glLinkProgram (GLuint program);
__attribute__((visibility("default"))) void glPixelStorei (GLenum pname, GLint param);
__attribute__((visibility("default"))) void glPolygonOffset (GLfloat factor, GLfloat units);
__attribute__((visibility("default"))) void glReadPixels (GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid* pixels);
__attribute__((visibility("default"))) void glReleaseShaderCompiler (void);
__attribute__((visibility("default"))) void glRenderbufferStorage (GLenum target, GLenum internalformat, GLsizei width, GLsizei height);
__attribute__((visibility("default"))) void glSampleCoverage (GLclampf value, GLboolean invert);
__attribute__((visibility("default"))) void glScissor (GLint x, GLint y, GLsizei width, GLsizei height);
__attribute__((visibility("default"))) void glShaderBinary (GLsizei n, const GLuint* shaders, GLenum binaryformat, const GLvoid* binary, GLsizei length);
__attribute__((visibility("default"))) void glShaderSource (GLuint shader, GLsizei count, const GLchar** string, const GLint* length);
__attribute__((visibility("default"))) void glStencilFunc (GLenum func, GLint ref, GLuint mask);
__attribute__((visibility("default"))) void glStencilFuncSeparate (GLenum face, GLenum func, GLint ref, GLuint mask);
__attribute__((visibility("default"))) void glStencilMask (GLuint mask);
__attribute__((visibility("default"))) void glStencilMaskSeparate (GLenum face, GLuint mask);
__attribute__((visibility("default"))) void glStencilOp (GLenum fail, GLenum zfail, GLenum zpass);
__attribute__((visibility("default"))) void glStencilOpSeparate (GLenum face, GLenum fail, GLenum zfail, GLenum zpass);
__attribute__((visibility("default"))) void glTexImage2D (GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid* pixels);
__attribute__((visibility("default"))) void glTexParameterf (GLenum target, GLenum pname, GLfloat param);
__attribute__((visibility("default"))) void glTexParameterfv (GLenum target, GLenum pname, const GLfloat* params);
__attribute__((visibility("default"))) void glTexParameteri (GLenum target, GLenum pname, GLint param);
__attribute__((visibility("default"))) void glTexParameteriv (GLenum target, GLenum pname, const GLint* params);
__attribute__((visibility("default"))) void glTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid* pixels);
__attribute__((visibility("default"))) void glUniform1f (GLint location, GLfloat x);
__attribute__((visibility("default"))) void glUniform1fv (GLint location, GLsizei count, const GLfloat* v);
__attribute__((visibility("default"))) void glUniform1i (GLint location, GLint x);
__attribute__((visibility("default"))) void glUniform1iv (GLint location, GLsizei count, const GLint* v);
__attribute__((visibility("default"))) void glUniform2f (GLint location, GLfloat x, GLfloat y);
__attribute__((visibility("default"))) void glUniform2fv (GLint location, GLsizei count, const GLfloat* v);
__attribute__((visibility("default"))) void glUniform2i (GLint location, GLint x, GLint y);
__attribute__((visibility("default"))) void glUniform2iv (GLint location, GLsizei count, const GLint* v);
__attribute__((visibility("default"))) void glUniform3f (GLint location, GLfloat x, GLfloat y, GLfloat z);
__attribute__((visibility("default"))) void glUniform3fv (GLint location, GLsizei count, const GLfloat* v);
__attribute__((visibility("default"))) void glUniform3i (GLint location, GLint x, GLint y, GLint z);
__attribute__((visibility("default"))) void glUniform3iv (GLint location, GLsizei count, const GLint* v);
__attribute__((visibility("default"))) void glUniform4f (GLint location, GLfloat x, GLfloat y, GLfloat z, GLfloat w);
__attribute__((visibility("default"))) void glUniform4fv (GLint location, GLsizei count, const GLfloat* v);
__attribute__((visibility("default"))) void glUniform4i (GLint location, GLint x, GLint y, GLint z, GLint w);
__attribute__((visibility("default"))) void glUniform4iv (GLint location, GLsizei count, const GLint* v);
__attribute__((visibility("default"))) void glUniformMatrix2fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
__attribute__((visibility("default"))) void glUniformMatrix3fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
__attribute__((visibility("default"))) void glUniformMatrix4fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
__attribute__((visibility("default"))) void glUseProgram (GLuint program);
__attribute__((visibility("default"))) void glValidateProgram (GLuint program);
__attribute__((visibility("default"))) void glVertexAttrib1f (GLuint indx, GLfloat x);
__attribute__((visibility("default"))) void glVertexAttrib1fv (GLuint indx, const GLfloat* values);
__attribute__((visibility("default"))) void glVertexAttrib2f (GLuint indx, GLfloat x, GLfloat y);
__attribute__((visibility("default"))) void glVertexAttrib2fv (GLuint indx, const GLfloat* values);
__attribute__((visibility("default"))) void glVertexAttrib3f (GLuint indx, GLfloat x, GLfloat y, GLfloat z);
__attribute__((visibility("default"))) void glVertexAttrib3fv (GLuint indx, const GLfloat* values);
__attribute__((visibility("default"))) void glVertexAttrib4f (GLuint indx, GLfloat x, GLfloat y, GLfloat z, GLfloat w);
__attribute__((visibility("default"))) void glVertexAttrib4fv (GLuint indx, const GLfloat* values);
__attribute__((visibility("default"))) void glVertexAttribPointer (GLuint indx, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const GLvoid* ptr);
__attribute__((visibility("default"))) void glViewport (GLint x, GLint y, GLsizei width, GLsizei height);
